// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include <lvgl.h>
#include <string>

void ui_main_screen_init(void)
{
    // Main screen
    ui_screen = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_screen, LV_OBJ_FLAG_SCROLLABLE );
    lv_obj_set_style_bg_color(ui_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    // /* Create simple label */
    // lv_obj_t *label = lv_label_create( ui_screen );
    // lv_label_set_text( label, "Hello Ardino and LVGL!");
    // lv_obj_align( label, LV_ALIGN_CENTER, 0, 0 );
    
    // auto screen_width = LV_HOR_RES;
    // auto screen_hight = LV_VER_RES;

    // auto widget_width = (screen_width - separator_size) / 2;

    // // Altimeter
    // ui_widget_init(ui_screen, altimeter_widget, 0, 0, widget_width, screen_hight, alt_value, alt_unit);

    // // Pitch
    // ui_widget_init(ui_screen, pitch_widget, (widget_width + separator_size), 0, widget_width, screen_hight, pitch_value, pitch_unit, -20);
}