[env:apple]
platform = native@^1.2.1
lib_compat_mode = off
build_type = debug

lib_ignore =
	AudioOutputWithCallback
	Network
	Radio
	ES8311

lib_deps = 
	${env.lib_deps}
	; https://github.com/lovyan03/LovyanGFX.git#develop
	; https://github.com/pschatzmann/Arduino-Emulator.git
	lovyan03/LovyanGFX@^1.2.29

build_flags =
	${env.build_flags}
	-Winconsistent-missing-override

	-DIS_DESKTOP_WITH_TIME_ONLY
	;-DIS_MIN_DESKTOP
	;-DIS_DESKTOP
	;-DUSE_WIFI
	-DEXIT_ON_STOP

	-DUSE_DEFAULT_STDLIB
	-D HELIX_LOGGING_ACTIVE=false
	-DDEFINE_MAIN

	-DLGFX_BACKEND
	-DLGFX_AUTODETECT

  -lSDL2
  -lSDL2_ttf
	-llibportaudio

	-I /opt/homebrew/Cellar/portaudio/19.7.0/include
	-L /opt/homebrew/Cellar/portaudio/19.7.0/lib

	-I ${sysenv.HOMEBREW_PREFIX}/include/SDL2
	-L ${sysenv.HOMEBREW_PREFIX}/lib

; Controls
	-D MENU_PIN_A=35
	-D MENU_PIN_B=34
	-D MENU_BUTTON=32
	
	-D VOLUME_PIN_A=04
	-D VOLUME_PIN_B=21
	-D VOLUME_BUTTON=15
	
; [env:local_win]
; platform = native@^1.2.1
; build_flags =
;		${env.build_flags}
; 	-lSDL2
; 	-DSDL_MAIN_HANDLED
; 	-I E:/Sources/SDL2-2.0.10/include
; 	-L E:/Sources/SDL2-2.0.10/lib