# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QSizePolicy,
    QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(248, 261)
        Widget.setStyleSheet(u"")
        self.frame = QFrame(Widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 231, 241))
        self.frame.setStyleSheet(u"border-radius: 16px;\n"
"background:rgba(50, 50, 50, 200);\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gpu_load = QLabel(self.frame)
        self.gpu_load.setObjectName(u"gpu_load")
        self.gpu_load.setGeometry(QRect(80, 11, 41, 16))
        font = QFont()
        font.setFamilies([u"Arial Black"])
        font.setPointSize(17)
        self.gpu_load.setFont(font)
        self.gpu_load.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.gpu_load.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gpu_tdp = QLabel(self.frame)
        self.gpu_tdp.setObjectName(u"gpu_tdp")
        self.gpu_tdp.setGeometry(QRect(80, 41, 41, 16))
        self.gpu_tdp.setFont(font)
        self.gpu_tdp.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.gpu_tdp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gpu = QLabel(self.frame)
        self.gpu.setObjectName(u"gpu")
        self.gpu.setGeometry(QRect(10, 11, 58, 16))
        self.gpu.setFont(font)
        self.gpu.setStyleSheet(u"color: rgb(52, 235, 122);\n"
"background-color: argb(0, 0, 0, 0);")
        self.gpu_tdp_unit = QLabel(self.frame)
        self.gpu_tdp_unit.setObjectName(u"gpu_tdp_unit")
        self.gpu_tdp_unit.setGeometry(QRect(120, 41, 17, 16))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(13)
        self.gpu_tdp_unit.setFont(font1)
        self.gpu_tdp_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.gpu_tdp_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu_temp_unit = QLabel(self.frame)
        self.cpu_temp_unit.setObjectName(u"cpu_temp_unit")
        self.cpu_temp_unit.setGeometry(QRect(200, 81, 17, 16))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(13)
        font2.setItalic(True)
        self.cpu_temp_unit.setFont(font2)
        self.cpu_temp_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.cpu_temp_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.fps = QLabel(self.frame)
        self.fps.setObjectName(u"fps")
        self.fps.setGeometry(QRect(10, 211, 58, 16))
        font3 = QFont()
        font3.setFamilies([u"Arial Black"])
        font3.setPointSize(18)
        font3.setBold(True)
        self.fps.setFont(font3)
        self.fps.setAutoFillBackground(False)
        self.fps.setStyleSheet(u"color: rgb(217, 52, 235);\n"
"background-color: argb(0, 0, 0, 0);")
        self.gpu_temp_unit = QLabel(self.frame)
        self.gpu_temp_unit.setObjectName(u"gpu_temp_unit")
        self.gpu_temp_unit.setGeometry(QRect(200, 11, 17, 16))
        self.gpu_temp_unit.setFont(font2)
        self.gpu_temp_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.gpu_temp_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu_load_unit = QLabel(self.frame)
        self.cpu_load_unit.setObjectName(u"cpu_load_unit")
        self.cpu_load_unit.setGeometry(QRect(120, 81, 17, 20))
        self.cpu_load_unit.setFont(font1)
        self.cpu_load_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.cpu_load_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gpu_temp = QLabel(self.frame)
        self.gpu_temp.setObjectName(u"gpu_temp")
        self.gpu_temp.setGeometry(QRect(160, 11, 41, 16))
        self.gpu_temp.setFont(font)
        self.gpu_temp.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.gpu_temp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ram_used = QLabel(self.frame)
        self.ram_used.setObjectName(u"ram_used")
        self.ram_used.setGeometry(QRect(80, 171, 41, 16))
        self.ram_used.setFont(font)
        self.ram_used.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.ram_used.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gpu_load_unit = QLabel(self.frame)
        self.gpu_load_unit.setObjectName(u"gpu_load_unit")
        self.gpu_load_unit.setGeometry(QRect(120, 11, 17, 16))
        self.gpu_load_unit.setFont(font1)
        self.gpu_load_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.gpu_load_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu_temp = QLabel(self.frame)
        self.cpu_temp.setObjectName(u"cpu_temp")
        self.cpu_temp.setGeometry(QRect(160, 81, 41, 16))
        self.cpu_temp.setFont(font)
        self.cpu_temp.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.cpu_temp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu = QLabel(self.frame)
        self.cpu.setObjectName(u"cpu")
        self.cpu.setGeometry(QRect(10, 81, 58, 16))
        self.cpu.setFont(font3)
        self.cpu.setAutoFillBackground(False)
        self.cpu.setStyleSheet(u"color: rgb(52, 137, 235);\n"
"background-color: argb(0, 0, 0, 0);")
        self.cpu_tdp_unit = QLabel(self.frame)
        self.cpu_tdp_unit.setObjectName(u"cpu_tdp_unit")
        self.cpu_tdp_unit.setGeometry(QRect(120, 101, 17, 16))
        self.cpu_tdp_unit.setFont(font1)
        self.cpu_tdp_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.cpu_tdp_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ram = QLabel(self.frame)
        self.ram.setObjectName(u"ram")
        self.ram.setGeometry(QRect(10, 171, 58, 16))
        self.ram.setFont(font3)
        self.ram.setAutoFillBackground(False)
        self.ram.setStyleSheet(u"color: rgb(235, 52, 88);\n"
"background-color: argb(0, 0, 0, 0);")
        self.vram_unit_2 = QLabel(self.frame)
        self.vram_unit_2.setObjectName(u"vram_unit_2")
        self.vram_unit_2.setGeometry(QRect(120, 171, 27, 16))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(13)
        font4.setBold(False)
        font4.setItalic(True)
        self.vram_unit_2.setFont(font4)
        self.vram_unit_2.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.vram_unit_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu_load = QLabel(self.frame)
        self.cpu_load.setObjectName(u"cpu_load")
        self.cpu_load.setGeometry(QRect(80, 81, 41, 16))
        self.cpu_load.setFont(font)
        self.cpu_load.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.cpu_load.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cpu_tdp = QLabel(self.frame)
        self.cpu_tdp.setObjectName(u"cpu_tdp")
        self.cpu_tdp.setGeometry(QRect(80, 101, 41, 16))
        self.cpu_tdp.setFont(font)
        self.cpu_tdp.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.cpu_tdp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.vram_used = QLabel(self.frame)
        self.vram_used.setObjectName(u"vram_used")
        self.vram_used.setGeometry(QRect(80, 141, 41, 16))
        self.vram_used.setFont(font)
        self.vram_used.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.vram_used.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.fps_value = QLabel(self.frame)
        self.fps_value.setObjectName(u"fps_value")
        self.fps_value.setGeometry(QRect(80, 211, 41, 16))
        self.fps_value.setFont(font)
        self.fps_value.setStyleSheet(u"background-color: argb(0, 0, 0, 0);")
        self.fps_value.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.vram = QLabel(self.frame)
        self.vram.setObjectName(u"vram")
        self.vram.setGeometry(QRect(10, 141, 58, 16))
        self.vram.setFont(font3)
        self.vram.setAutoFillBackground(False)
        self.vram.setStyleSheet(u"color: rgb(235, 52, 204);\n"
"background-color: argb(0, 0, 0, 0);")
        self.vram_unit = QLabel(self.frame)
        self.vram_unit.setObjectName(u"vram_unit")
        self.vram_unit.setGeometry(QRect(120, 140, 27, 16))
        self.vram_unit.setFont(font4)
        self.vram_unit.setStyleSheet(u"background-color: argb(0, 0, 0, 0);\n"
"color: rgb(150,150,150);")
        self.vram_unit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        self.gpu_load.setText(QCoreApplication.translate("Widget", u"100", None))
        self.gpu_tdp.setText(QCoreApplication.translate("Widget", u"100", None))
        self.gpu.setText(QCoreApplication.translate("Widget", u"GPU", None))
        self.gpu_tdp_unit.setText(QCoreApplication.translate("Widget", u"W", None))
        self.cpu_temp_unit.setText(QCoreApplication.translate("Widget", u"\u00b0C", None))
        self.fps.setText(QCoreApplication.translate("Widget", u"FPS", None))
        self.gpu_temp_unit.setText(QCoreApplication.translate("Widget", u"\u00b0C", None))
        self.cpu_load_unit.setText(QCoreApplication.translate("Widget", u"%", None))
        self.gpu_temp.setText(QCoreApplication.translate("Widget", u"45", None))
        self.ram_used.setText(QCoreApplication.translate("Widget", u"4.2", None))
        self.gpu_load_unit.setText(QCoreApplication.translate("Widget", u"%", None))
        self.cpu_temp.setText(QCoreApplication.translate("Widget", u"45", None))
        self.cpu.setText(QCoreApplication.translate("Widget", u"CPU", None))
        self.cpu_tdp_unit.setText(QCoreApplication.translate("Widget", u"W", None))
        self.ram.setText(QCoreApplication.translate("Widget", u"RAM", None))
        self.vram_unit_2.setText(QCoreApplication.translate("Widget", u"GiB", None))
        self.cpu_load.setText(QCoreApplication.translate("Widget", u"100", None))
        self.cpu_tdp.setText(QCoreApplication.translate("Widget", u"100", None))
        self.vram_used.setText(QCoreApplication.translate("Widget", u"4.2", None))
        self.fps_value.setText(QCoreApplication.translate("Widget", u"60", None))
        self.vram.setText(QCoreApplication.translate("Widget", u"VRAM", None))
        self.vram_unit.setText(QCoreApplication.translate("Widget", u"GiB", None))
        pass
    # retranslateUi

