// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

const int separator_size = 4;
const int separator_width = 170;

const int background_color = 0x000000;
const int background_light_color = 0x00F34F;

const int primary_color = 0xFFFFFF;
const int secondary_color = 0x969696;
const int hi_color = 0xED001E;

void ui_set_alt(int value)
{

}

void ui_main_screen_init(void)
{
    // Main screen
    ui_screen = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Pitch Max
    ui_pitch_max = lv_label_create(ui_screen);
    lv_obj_set_width( ui_pitch_max, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_pitch_max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_pitch_max, 140 );
    lv_obj_set_y( ui_pitch_max, 92 );
    lv_obj_set_align( ui_pitch_max, LV_ALIGN_CENTER );
    lv_label_set_text(ui_pitch_max,"-10");
    lv_obj_set_style_text_color(ui_pitch_max, lv_color_hex(primary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_pitch_max, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pitch_max, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_pitch_max_unit = lv_label_create(ui_screen);
    lv_obj_set_width( ui_pitch_max_unit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_pitch_max_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_pitch_max_unit, 174 );
    lv_obj_set_y( ui_pitch_max_unit, 89 );
    lv_obj_set_align( ui_pitch_max_unit, LV_ALIGN_CENTER );
    lv_label_set_text(ui_pitch_max_unit,"°");
    lv_obj_set_style_text_color(ui_pitch_max_unit, lv_color_hex(secondary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_pitch_max_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pitch_max_unit, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Alt Max
    ui_alt_max = lv_label_create(ui_screen);
    lv_obj_set_width( ui_alt_max, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_alt_max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_alt_max, -144 );
    lv_obj_set_y( ui_alt_max, 90 );
    lv_obj_set_align( ui_alt_max, LV_ALIGN_CENTER );
    lv_label_set_text(ui_alt_max,"3500");
    lv_obj_set_style_text_color(ui_alt_max, lv_color_hex(primary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_alt_max, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alt_max, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_alt_max_unit = lv_label_create(ui_screen);
    lv_obj_set_width( ui_alt_max_unit, LV_SIZE_CONTENT);
    lv_obj_set_height( ui_alt_max_unit, LV_SIZE_CONTENT);
    lv_obj_set_x( ui_alt_max_unit, -77 );
    lv_obj_set_y( ui_alt_max_unit, 89 );
    lv_obj_set_align( ui_alt_max_unit, LV_ALIGN_CENTER );
    lv_label_set_text(ui_alt_max_unit,"m");
    lv_obj_set_style_text_color(ui_alt_max_unit, lv_color_hex(secondary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_font(ui_alt_max_unit, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Pitch background
    ui_pitch_background = lv_obj_create(ui_screen);
    lv_obj_remove_style_all(ui_pitch_background);
    lv_obj_set_width( ui_pitch_background, lv_pct(46));
    lv_obj_set_height( ui_pitch_background, lv_pct(70));
    lv_obj_set_x( ui_pitch_background, lv_pct(26) );
    lv_obj_set_y( ui_pitch_background, lv_pct(-12) );
    lv_obj_set_align( ui_pitch_background, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_pitch_background, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_pitch_background, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pitch_background, lv_color_hex(background_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_pitch_background, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Pitch
    ui_pitch = lv_label_create(ui_pitch_background);
    lv_obj_set_width( ui_pitch, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_pitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_pitch, -5 );
    lv_obj_set_y( ui_pitch, -5 );
    lv_obj_set_align( ui_pitch, LV_ALIGN_CENTER );
    lv_label_set_text(ui_pitch,"-20");
    lv_obj_set_style_text_color(ui_pitch, lv_color_hex(primary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_pitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pitch, &ui_font_conthraxfont48, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_pitch_unit = lv_label_create(ui_pitch_background);
    lv_obj_set_width( ui_pitch_unit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_pitch_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_pitch_unit, 59 );
    lv_obj_set_y( ui_pitch_unit, -20 );
    lv_obj_set_align( ui_pitch_unit, LV_ALIGN_CENTER );
    lv_label_set_text(ui_pitch_unit,"°");
    lv_obj_set_style_text_color(ui_pitch_unit, lv_color_hex(secondary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_pitch_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pitch_unit, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Alt background
    ui_alt_background = lv_obj_create(ui_screen);
    lv_obj_remove_style_all(ui_alt_background);
    lv_obj_set_width( ui_alt_background, lv_pct(47));
    lv_obj_set_height( ui_alt_background, lv_pct(69));
    lv_obj_set_x( ui_alt_background, lv_pct(-24) );
    lv_obj_set_y( ui_alt_background, lv_pct(-12) );
    lv_obj_set_align( ui_alt_background, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_alt_background, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_alt_background, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alt_background, lv_color_hex(background_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_alt_background, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    
    // Altimeter
    ui_alt = lv_label_create(ui_alt_background);
    lv_obj_set_width( ui_alt, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_alt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_alt, LV_ALIGN_CENTER );
    lv_label_set_text(ui_alt,"3120");
    lv_obj_set_style_text_color(ui_alt, lv_color_hex(primary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_alt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alt, &ui_font_conthraxfont48, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_alt_unit = lv_label_create(ui_alt_background);
    lv_obj_set_width( ui_alt_unit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_alt_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_alt_unit, 95 );
    lv_obj_set_y( ui_alt_unit, 5 );
    lv_obj_set_align( ui_alt_unit, LV_ALIGN_CENTER );
    lv_label_set_text(ui_alt_unit,"m");
    lv_obj_set_style_text_color(ui_alt_unit, lv_color_hex(secondary_color), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_alt_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alt_unit, &ui_font_conthraxfont26, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Styles
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_radius(&style, 0);

    static lv_grad_dsc_t grad_dsc;
    grad_dsc.dir = LV_GRAD_DIR_HOR;
    grad_dsc.stops_count = 4;

    grad_dsc.stops[0].color = lv_color_hex(background_color);
    grad_dsc.stops[0].frac = 50;

    grad_dsc.stops[1].color = lv_color_hex(secondary_color);
    grad_dsc.stops[1].frac = 100;

    grad_dsc.stops[2].color = lv_color_hex(secondary_color);
    grad_dsc.stops[2].frac = 180;

    grad_dsc.stops[3].color = lv_color_hex(background_color);
    grad_dsc.stops[3].frac = 255;

    lv_style_set_bg_grad(&style, &grad_dsc);

    // Left gradient
    ui_left_hor_separator = lv_obj_create(ui_screen);
    lv_obj_set_width( ui_left_hor_separator, separator_width);
    lv_obj_set_height( ui_left_hor_separator, separator_size);
    lv_obj_set_x( ui_left_hor_separator, 30 );
    lv_obj_set_y( ui_left_hor_separator, 180 );
    lv_obj_set_align( ui_left_hor_separator, LV_ALIGN_TOP_LEFT );
    lv_obj_clear_flag( ui_left_hor_separator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_add_style(ui_left_hor_separator, &style, 0);

    // Vertical line
    ui_vertical_separator = lv_obj_create(ui_screen);
    lv_obj_set_width( ui_vertical_separator, 4);
    lv_obj_set_height( ui_vertical_separator, lv_pct(107));
    lv_obj_set_x( ui_vertical_separator, 10 );
    lv_obj_set_y( ui_vertical_separator, -4 );
    lv_obj_set_align( ui_vertical_separator, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_vertical_separator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_vertical_separator, lv_color_hex(0x929292), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_vertical_separator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    // Right separator
    ui_right_hor_separator = lv_obj_create(ui_screen);
    lv_obj_set_width( ui_right_hor_separator, separator_width);
    lv_obj_set_height( ui_right_hor_separator, separator_size);
    lv_obj_set_x( ui_right_hor_separator, 310 );
    lv_obj_set_y( ui_right_hor_separator, 180 );
    lv_obj_set_align( ui_right_hor_separator, LV_ALIGN_TOP_LEFT );
    lv_obj_clear_flag( ui_right_hor_separator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_add_style(ui_right_hor_separator, &style, 0);
}
