[env:esp32-motor-ctrl-bldc]
extends = env:esp_legacy_base
board = esp-wrover-kit
upload_speed = 115200
monitor_speed = 115200
lib_deps = 
	${env:esp_legacy_base.lib_deps}
build_flags = 
	${env:esp_legacy_base.build_flags}
	-D DEVICE_ID=bldc_config
	-D CONFIG_NAME=driver_config_bldc
	-D CONTROLS_NAME=config_json
	; Board capabilities
  -D LED_PIN=2
